# migrations/001_seed_users.py

import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "data.db")


def migrate():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    users = [
        {
            "customId": "000001",
            "username": "admin",
            "password": "admin",
            "email": "admin@admin.com",
            "access_level": 1,
            "account_status": "active",
            "is_locked": False,
            "temporary_password": None,
            "created_at": "2025-06-08 13:52:15",
            "updated_at": "2025-06-08 13:52:15",
        },
        {
            "customId": "000002",
            "username": "jean",
            "password": "mypassword",
            "email": "admin@admin.com",
            "access_level": 1,
            "account_status": "active",
            "is_locked": False,
            "temporary_password": None,
            "created_at": "2025-06-08 13:52:15",
            "updated_at": "2025-06-08 13:52:15",
        },
        {
            "customId": "000003",
            "username": "staff",
            "password": "staff",
            "email": "admin@admin.com",
            "access_level": 1,
            "account_status": "active",
            "is_locked": False,
            "temporary_password": None,
            "created_at": "2025-06-08 13:52:15",
            "updated_at": "2025-06-08 13:52:15",
        },
        {
            "customId": "000004",
            "username": "jane_doe",
            "password": "password123",
            "email": "jane@example.com",
            "access_level": 2,
            "account_status": "active",
            "is_locked": False,
            "temporary_password": None,
            "created_at": "2025-06-08 13:55:00",
            "updated_at": "2025-06-08 13:55:00",
        },
        {
            "customId": "000005",
            "username": "john_smith",
            "password": "john123",
            "email": "john@example.com",
            "access_level": 2,
            "account_status": "active",
            "is_locked": False,
            "temporary_password": None,
            "created_at": "2025-06-08 13:55:01",
            "updated_at": "2025-06-08 13:55:01",
        },
        {
            "customId": "000006",
            "username": "susan89",
            "password": "susan89",
            "email": "susan@example.com",
            "access_level": 1,
            "account_status": "inactive",
            "is_locked": False,
            "temporary_password": None,
            "created_at": "2025-06-08 13:55:02",
            "updated_at": "2025-06-08 13:55:02",
        },
        {
            "customId": "000007",
            "username": "mike22",
            "password": "mikepass",
            "email": "mike@example.com",
            "access_level": 3,
            "account_status": "active",
            "is_locked": True,
            "temporary_password": "temp123",
            "created_at": "2025-06-08 13:55:03",
            "updated_at": "2025-06-08 13:55:03",
        },
        {
            "customId": "000008",
            "username": "emma",
            "password": "emma2025",
            "email": "emma@example.com",
            "access_level": 2,
            "account_status": "active",
            "is_locked": False,
            "temporary_password": None,
            "created_at": "2025-06-08 13:55:04",
            "updated_at": "2025-06-08 13:55:04",
        },
        {
            "customId": "000009",
            "username": "liam",
            "password": "liam2025",
            "email": "liam@example.com",
            "access_level": 2,
            "account_status": "locked",
            "is_locked": True,
            "temporary_password": "resetMe",
            "created_at": "2025-06-08 13:55:05",
            "updated_at": "2025-06-08 13:55:05",
        },
        {
            "customId": "000010",
            "username": "olivia",
            "password": "olivia321",
            "email": "olivia@example.com",
            "access_level": 1,
            "account_status": "active",
            "is_locked": False,
            "temporary_password": None,
            "created_at": "2025-06-08 13:55:06",
            "updated_at": "2025-06-08 13:55:06",
        },
        {
            "customId": "000011",
            "username": "liam",
            "password": "liam123",
            "email": "liam@example.com",
            "access_level": 2,
            "account_status": "active",
            "is_locked": False,
            "temporary_password": None,
            "created_at": "2025-06-08 14:00:00",
            "updated_at": "2025-06-08 14:00:00",
        },
        {
            "customId": "000012",
            "username": "emma",
            "password": "emma456",
            "email": "emma@example.com",
            "access_level": 1,
            "account_status": "inactive",
            "is_locked": True,
            "temporary_password": "temp456",
            "created_at": "2025-06-08 14:05:00",
            "updated_at": "2025-06-08 14:05:00",
        },
        {
            "customId": "000013",
            "username": "noah",
            "password": "noah789",
            "email": "noah@example.com",
            "access_level": 3,
            "account_status": "active",
            "is_locked": False,
            "temporary_password": None,
            "created_at": "2025-06-08 14:10:00",
            "updated_at": "2025-06-08 14:10:00",
        },
        {
            "customId": "000014",
            "username": "ava",
            "password": "ava321",
            "email": "ava@example.com",
            "access_level": 2,
            "account_status": "active",
            "is_locked": False,
            "temporary_password": None,
            "created_at": "2025-06-08 14:15:00",
            "updated_at": "2025-06-08 14:15:00",
        },
        {
            "customId": "000015",
            "username": "oliver",
            "password": "oliver654",
            "email": "oliver@example.com",
            "access_level": 1,
            "account_status": "inactive",
            "is_locked": True,
            "temporary_password": "temp654",
            "created_at": "2025-06-08 14:20:00",
            "updated_at": "2025-06-08 14:20:00",
        },
        {
            "customId": "000016",
            "username": "sophia",
            "password": "sophia987",
            "email": "sophia@example.com",
            "access_level": 3,
            "account_status": "active",
            "is_locked": False,
            "temporary_password": None,
            "created_at": "2025-06-08 14:25:00",
            "updated_at": "2025-06-08 14:25:00",
        },
        {
            "customId": "000017",
            "username": "james",
            "password": "james321",
            "email": "james@example.com",
            "access_level": 2,
            "account_status": "active",
            "is_locked": False,
            "temporary_password": None,
            "created_at": "2025-06-08 14:30:00",
            "updated_at": "2025-06-08 14:30:00",
        },
        {
            "customId": "000018",
            "username": "isabella",
            "password": "isabella123",
            "email": "isabella@example.com",
            "access_level": 1,
            "account_status": "locked",
            "is_locked": True,
            "temporary_password": "temp123",
            "created_at": "2025-06-08 14:35:00",
            "updated_at": "2025-06-08 14:35:00",
        },
        {
            "customId": "000019",
            "username": "william",
            "password": "william456",
            "email": "william@example.com",
            "access_level": 3,
            "account_status": "active",
            "is_locked": False,
            "temporary_password": None,
            "created_at": "2025-06-08 14:40:00",
            "updated_at": "2025-06-08 14:40:00",
        },
        {
            "customId": "000020",
            "username": "mia",
            "password": "mia789",
            "email": "mia@example.com",
            "access_level": 2,
            "account_status": "active",
            "is_locked": False,
            "temporary_password": None,
            "created_at": "2025-06-08 14:45:00",
            "updated_at": "2025-06-08 14:45:00",
        },
    ]

    for user in users:
        cursor.execute(
            """
            INSERT INTO users (
                customId, username, password, email, access_level,
                account_status, is_locked, temporary_password,
                created_at, updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                user["customId"],
                user["username"],
                user["password"],
                user["email"],
                user["access_level"],
                user["account_status"],
                user["is_locked"],
                user["temporary_password"],
                user["created_at"],
                user["updated_at"],
            ),
        )

    conn.commit()
    conn.close()
    print("Seed migration 001_seed_users complete.")


if __name__ == "__main__":
    migrate()
